#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text()


def check(name: str, ok: bool) -> None:
    print(("PASS" if ok else "FAIL") + ": " + name)
    if not ok:
        raise SystemExit(1)


pp8 = read("tools/ds4_launch_dsv4_flash_pp8.sh")
pp4 = read("tools/ds4_launch_dsv4_flash_pp4_tp2_ep.sh")
guard = read("tools/ds4_200g_guard.sh")
preflight = read("tools/ds4_nccl_preflight.py")
rail_tcp = read("tools/ds4_rail_tcp_preflight.py")
relaunch = read("tools/ds4_relaunch_spark_service.py")
stop = read("tools/ds4_stop_spark_processes.py")
submit_pr = read("tools/ds4_submit_pr.py")
envs = read("vllm/envs.py")
ps = read("vllm/distributed/parallel_state.py")

check("PP8 enables PyNCCL tensor-dict by default for performance runs", 'VLLM_DS4_PP_PYNCCL_TENSOR_DICT:-1' in pp8)
check("PP8 stripes PyNCCL tensor-dict transfers by default", 'VLLM_DS4_PP_PYNCCL_TENSOR_DICT_STRIPES:-8' in pp8)
check("PP8 keeps the PP device communicator enabled by default", 'VLLM_DS4_PP_DISABLE_DEVICE_COMMUNICATOR:-0' in pp8)
check("PP8 requires CUDA device metadata for PP tensor dicts", 'VLLM_DS4_PP_DEVICE_TENSOR_DICT_METADATA:-1' in pp8 and "Pickled CPU PP metadata caused multi-second stage stalls" in pp8)
check("PyNCCL tensor-dict env exists as the required PP fast path", "VLLM_DS4_PP_PYNCCL_TENSOR_DICT" in envs)
check("PP device tensor-dict metadata env exists", "VLLM_DS4_PP_DEVICE_TENSOR_DICT_METADATA" in envs)
check("PyNCCL tensor-dict striping env exists", "VLLM_DS4_PP_PYNCCL_TENSOR_DICT_STRIPES" in envs)
check("PP tensor-dict TP all-gather env exists", "VLLM_DS4_PP_TENSOR_DICT_TP_ALL_GATHER" in envs)
check("TP process-group all-reduce escape hatch env exists", "VLLM_DS4_TP_PROCESS_GROUP_ALL_REDUCE" in envs)
check("TP device all-reduce requirement env exists", "VLLM_DS4_REQUIRE_DEVICE_TP_ALL_REDUCE" in envs)
check("parallel_state has DS4 PP PyNCCL tensor-dict gate", "_can_use_ds4_pynccl_tensor_dict" in ps or "_can_use_ds4_pp_pynccl_tensor_dict" in ps)
check("parallel_state has DS4 PP CUDA metadata header path", "_send_ds4_pp_device_metadata" in ps and "_recv_ds4_pp_device_metadata" in ps)
check("parallel_state avoids CPU object metadata on DS4 PP device metadata path", "VLLM_DS4_PP_DEVICE_TENSOR_DICT_METADATA" in ps and "Refusing CPU/Gloo metadata fallback" in ps)
check("parallel_state stripes DS4 PP PyNCCL tensor-dict payloads", "_ds4_pynccl_p2p_chunks" in ps)
check("parallel_state queues DS4 PP PyNCCL on a dedicated CUDA comm stream", "_get_ds4_pp_pynccl_stream" in ps and "torch.cuda.stream(comm_stream)" in ps)
check("parallel_state keeps receive payload waits stream-ordered", "_Ds4CudaStreamHandle" in ps and "torch.cuda.current_stream().wait_event(self._event)" in ps)
check("parallel_state synchronizes PP payload sends at the worker boundary", "cuda_p2p_tensors,\n            dst,\n            torch.distributed.isend,\n            # PP sends must be globally complete before the worker starts" in ps and "synchronize_on_wait=True" in ps)
check("parallel_state sends DS4 PP metadata without waiting for the model stream", "wait_for_producer=False" in ps and "synchronize_on_wait=True" in ps)
check("parallel_state posts DS4 PP payload receives without waiting for local compute", "torch.distributed.irecv,\n            wait_for_producer=False" in ps)
check("parallel_state can disable PP tensor-dict TP all-gather", "VLLM_DS4_PP_TENSOR_DICT_TP_ALL_GATHER" in ps and 'self.unique_name.startswith("pp")' in ps)
check("parallel_state keeps DS4 TP process-group all-reduce opt-in only", "VLLM_DS4_TP_PROCESS_GROUP_ALL_REDUCE" in ps and 'self.unique_name.startswith("tp:")' in ps and "torch.distributed.all_reduce(output, group=self.device_group)" in ps)
check("CUDA communicator refuses TP process-group fallback when DS4 requires device all-reduce", "VLLM_DS4_REQUIRE_DEVICE_TP_ALL_REDUCE" in read("vllm/distributed/device_communicators/cuda_communicator.py") and "refusing torch process-group fallback for TP group" in read("vllm/distributed/device_communicators/cuda_communicator.py"))
check("PP4xTP2 launcher exists", 'TP_SIZE="${TP_SIZE:-2}"' in pp4 and 'PP_SIZE="${PP_SIZE:-4}"' in pp4)
check("PP4xTP2 launcher enforces 8x world geometry", 'requires NNODES=8 PP_SIZE=4 TP_SIZE=2' in pp4)
check("PP4xTP2 launcher enables expert parallel", "--enable-expert-parallel" in pp4)
check("PP4xTP2 launcher has 43-layer partition", 'DSV4_FLASH_PP_LAYER_PARTITION="7,11,14,11"' in pp4)
check("PP4xTP2 launcher defaults to bounded request admission waves", 'DSV4_SCHED_MAX_NEW_REQS_PER_STEP:-32' in pp4)
check("PP4xTP2 launcher defaults to bounded prefill token waves", 'DSV4_SCHED_MAX_NEW_PREFILL_TOKENS_PER_STEP:-32768' in pp4)
check("PP8 launcher defaults to bounded request admission waves", 'DSV4_SCHED_MAX_NEW_REQS_PER_STEP:-32' in pp8)
check("PP8 launcher defaults to bounded prefill token waves", 'DSV4_SCHED_MAX_NEW_PREFILL_TOKENS_PER_STEP:-32768' in pp8)
check("PP8 launcher hard-codes the front-loaded 43-layer partition", 'DSV4_FLASH_PP_LAYER_PARTITION="8,8,8,8,8,1,1,1"' in pp8)
check("PP8 launcher does not accept stale default partition overrides", "DSV4_FLASH_PP_LAYER_PARTITION_DEFAULT" not in pp8)
check("DSV4 launchers skip profile-only dummy sampler logits gather", "VLLM_DS4_PROFILE_SKIP_DUMMY_SAMPLER" in envs and 'VLLM_DS4_PROFILE_SKIP_DUMMY_SAMPLER:-1' in pp8 and 'VLLM_DS4_PROFILE_SKIP_DUMMY_SAMPLER:-1' in pp4)
check("DSV4 launchers skip explicit-KV memory profile forward", "VLLM_DS4_SKIP_EXPLICIT_KV_PROFILE_RUN" in envs and 'VLLM_DS4_SKIP_EXPLICIT_KV_PROFILE_RUN:-1' in pp8 and 'VLLM_DS4_SKIP_EXPLICIT_KV_PROFILE_RUN:-1' in pp4)
check("DSV4 launchers skip last-rank sampler warmup", "VLLM_DS4_SKIP_LAST_RANK_SAMPLER_WARMUP" in envs and 'VLLM_DS4_SKIP_LAST_RANK_SAMPLER_WARMUP:-1' in pp8 and 'VLLM_DS4_SKIP_LAST_RANK_SAMPLER_WARMUP:-1' in pp4)
check("PP4xTP2 launcher preserves final-only nonstreaming output", "VLLM_DS4_FINAL_ONLY_NONSTREAMING" in pp4)
check("PP4xTP2 launcher preserves fused execute/sample default", "VLLM_DS4_FUSED_EXECUTE_SAMPLE" in pp4)
check("PP4xTP2 launcher serves existing DS4 DSV4 API model by default", 'DSV4_SERVED_MODEL_NAME:-deepseek-v4-flash-pp8' in pp4)
check("PP4xTP2 launcher does not set PP-only global backend", 'export VLLM_DS4_PP_ONLY_GLOBAL_BACKEND=' not in pp4)
check("PP4xTP2 launcher fails early if PP-only global backend leaks in", "PP4xTP2xEP refuses VLLM_DS4_PP_ONLY_GLOBAL_BACKEND" in pp4)
check("PP4xTP2 launcher uses NCCL for global control", 'VLLM_DS4_DISTRIBUTED_BACKEND="${VLLM_DS4_DISTRIBUTED_BACKEND:-nccl}"' in pp4)
check("PP4xTP2 launcher refuses gloo/CPU global control", "gloo/CPU control paths hide PP transport regressions" in pp4)
check("PP4xTP2 launcher preflights required TP groups and PP P2P links", 'DS4_NCCL_PREFLIGHT_MODE="${DS4_NCCL_PREFLIGHT_MODE:-p2p_nccl}"' in pp4 and "DS4_NCCL_PREFLIGHT_GROUPS" in pp4)
check("PP4xTP2 launcher declares TP/EP pair collectives", "0,1;2,3;4,5;6,7" in pp4)
check("PP4xTP2 launcher declares directional PP boundary P2P pairs", "0-2;1-3;2-4;3-5;4-6;5-7" in pp4)
check("PP4xTP2 launcher uses unidirectional PP P2P preflight", 'DS4_NCCL_PREFLIGHT_P2P_DIRECTION="${DS4_NCCL_PREFLIGHT_P2P_DIRECTION:-unidirectional}"' in pp4)
check("PP4xTP2 launcher refuses pair-local NCCL view", "refuses DS4_200G_PAIR_LOCAL_NCCL=1" in pp4)
check("200G guard separates route validation IFNAME from NCCL IFNAME", "DS4_200G_NCCL_IFNAME" in guard and "nccl_ifnames_csv" in guard and "NCCL interface" in guard)
check("200G guard defaults NCCL socket transport to physical rail interfaces", 'socket_ifname="${DS4_200G_SOCKET_IFNAME:-$ifnames_csv}"' in guard and "NCCL routed socket interface" in guard)
check("200G guard pins IB HCA from NCCL IFNAME, not the full route list", 'ds4_200g_check_or_export NCCL_IB_HCA "$nccl_hcas_csv"' in guard)
check("200G guard supports explicit degraded-link bringup without hiding it", "DS4_200G_ALLOW_DEGRADED_LINKS" in guard and "excluding it from the effective DS4 fabric list" in guard)
check("200G guard uses configurable link-speed floor before measured TCP preflight", "DS4_200G_LINK_MIN_MBPS" in guard and "below DS4_200G_LINK_MIN_MBPS" in guard)
check("200G guard prints effective fabric list after degraded filtering", "effective DS4_200G_IFNAME" in guard and "effective DS4_200G_NCCL_IFNAME" in guard)
check("NCCL preflight prints NCCL interface override", '"DS4_200G_NCCL_IFNAME"' in preflight)
check("NCCL preflight has P2P bandwidth mode", "def _run_p2p_nccl_preflight(" in preflight and "DS4_NCCL_PREFLIGHT_P2P_PAIRS" in preflight)
check("NCCL preflight stripes P2P probes to match PP tensor transport", "DS4_NCCL_PREFLIGHT_P2P_STRIPES" in preflight and "_split_p2p_tensor" in preflight)
check("NCCL preflight separates directional PP P2P from TP pair collectives", "DS4_NCCL_PREFLIGHT_P2P_DIRECTION" in preflight and "pairwise NCCL group probes begin" in preflight)
check("NCCL collective bandwidth is warning-only during cable debug", "DS4_NCCL_PREFLIGHT_MIN_BUSBW_GBPS:-0" in guard)
check("NCCL preflight warns below old collective floor without failing launch", "DS4_NCCL_PREFLIGHT_WARN_BUSBW_GBPS" in preflight and "WARNING: DS4 NCCL preflight below warning threshold" in preflight and "DS4_NCCL_PREFLIGHT_WARN_BUSBW_GBPS:-8" in guard)
check("rail TCP preflight script exists", "ds4_transfer.fast_copy data-plane shape" in rail_tcp)
check("rail TCP preflight discovers route rails like fast_copy", "ip\", \"route\", \"show\"" in rail_tcp and "destination_ip=dst_ip" in rail_tcp)
check("rail TCP preflight uses iperf for the launch speed gate", "DS4_RAIL_TCP_PREFLIGHT_TOOL" in rail_tcp and "iperf" in rail_tcp and "--reportstyle C" not in rail_tcp and "-y" in rail_tcp)
check("rail TCP iperf parser uses the aggregate summary row", 'fields[5] != "-1"' in rail_tcp)
check("rail TCP iperf parser rejects zero-interval summaries", "DS4_RAIL_TCP_PREFLIGHT_MIN_REPORT_INTERVAL_S" in rail_tcp and "interval_s < min_interval_s" in rail_tcp)
check("rail TCP preflight holds inbound servers for the measurement window", "DS4_RAIL_TCP_PREFLIGHT_SERVER_HOLD_EXTRA_S" in rail_tcp and "hold_until = server_started_at + duration_s + hold_extra_s" in rail_tcp)
check("rail TCP preflight keeps servers alive long enough for slow ring ranks", 'DS4_RAIL_TCP_PREFLIGHT_SERVER_HOLD_EXTRA_S", "10.0"' in rail_tcp)
check("rail TCP clients retry until peer servers are ready", "DS4_RAIL_TCP_PREFLIGHT_CLIENT_RETRY_SLEEP_S" in rail_tcp and "while time.monotonic() < deadline" in rail_tcp)
check("rail TCP hard floor is expressed in Gbit/s", "DS4_RAIL_TCP_PREFLIGHT_MIN_GBIT_S" in rail_tcp and "fail_Gbit_s" in rail_tcp)
check("rail TCP warning floor prints measured Gbit/s without failing launch", "DS4_RAIL_TCP_PREFLIGHT_WARN_GBIT_S" in rail_tcp and "WARNING: DS4 rail TCP preflight below warning threshold" in rail_tcp)
check("rail TCP preflight binds explicit client source rail IPs", "nc -N -s {rail.source_ip}" in rail_tcp)
check("rail TCP preflight uses many unencrypted streams per edge", "DS4_RAIL_TCP_PREFLIGHT_STREAMS" in rail_tcp and "threading.Thread" in rail_tcp)
check("200G guard can run rail TCP preflight before NCCL", "ds4_run_rail_tcp_preflight" in guard and "ds4_rail_tcp_preflight.py" in guard)
check("Triton/AOT cache scope is derived from vLLM commit", "ds4_vllm_git_commit()" in guard and "git -C \"$root\" rev-parse --short=12 HEAD" in guard)
check("Triton/AOT cache scope includes launch shape", "ds4_triton_cache_scope()" in guard and "DSV4_FLASH_PP_LAYER_PARTITION" in guard and "DSV4_MAX_NUM_SEQS" in guard and "DSV4_MAX_NUM_BATCHED_TOKENS" in guard)
check("Triton/AOT cache root is scoped below the service root", 'default_work_root="$default_work_base/$cache_scope"' in guard and 'export DS4_TRITON_CACHE_SCOPE="$cache_scope"' in guard)
check("Triton/AOT cache log prints cache scope and VLLM cache root", "cache_scope=$DS4_TRITON_CACHE_SCOPE" in guard and "VLLM_CACHE_ROOT=$VLLM_CACHE_ROOT" in guard)
check("DSV4 PP8 enables rail TCP fabric preflight", "DS4_RAIL_TCP_PREFLIGHT_ACTIVE" in pp8 and "ds4_run_rail_tcp_preflight" in pp8)
check("DSV4 PP8 rail TCP default fails below 10 Gbit/s and warns below old floor", "DS4_RAIL_TCP_PREFLIGHT_MIN_GBIT_S:-10" in pp8 and "DS4_RAIL_TCP_PREFLIGHT_WARN_GBIT_S:-64" in pp8)
check("DSV4 PP4xTP2 enables rail TCP physical fabric preflight", "DS4_RAIL_TCP_PREFLIGHT_ACTIVE" in pp4 and "DS4_RAIL_TCP_PREFLIGHT_PAIRS" in pp4)
check("DSV4 PP4xTP2 keeps NCCL P2P bandwidth warning-only during cable debug", 'DS4_NCCL_PREFLIGHT_MIN_P2P_GBPS="${DS4_NCCL_PREFLIGHT_MIN_P2P_GBPS:-0}"' in pp4 and "DS4_NCCL_PREFLIGHT_WARN_P2P_GBPS" in pp4 and "WARNING: DS4 NCCL P2P preflight below warning threshold" in preflight)
check("PP4xTP2 launcher refuses CPU-staged PP tensor dict fallback", "refuses VLLM_DS4_PP_CPU_STAGED_TENSOR_DICT=1" in pp4)
check("PP4xTP2 launcher requires PyNCCL PP tensor dict fast path", "requires VLLM_DS4_PP_PYNCCL_TENSOR_DICT=1" in pp4)
check("PP4xTP2 launcher requires PP device metadata fast path", "requires VLLM_DS4_PP_DEVICE_TENSOR_DICT_METADATA=1" in pp4 and 'VLLM_DS4_PP_DEVICE_TENSOR_DICT_METADATA:-1' in pp4)
check("PP4xTP2 launcher disables PP tensor-dict TP all-gather", 'VLLM_DS4_PP_TENSOR_DICT_TP_ALL_GATHER:-0' in pp4 and "refuses VLLM_DS4_PP_TENSOR_DICT_TP_ALL_GATHER=1" in pp4)
check("PP4xTP2 launcher stripes PyNCCL tensor-dict transfers by default", 'VLLM_DS4_PP_PYNCCL_TENSOR_DICT_STRIPES:-8' in pp4)
check("PP4xTP2 launcher defaults TP all-reduce to the device communicator", 'VLLM_DS4_TP_PROCESS_GROUP_ALL_REDUCE:-0' in pp4 and 'VLLM_DS4_REQUIRE_DEVICE_TP_ALL_REDUCE:-1' in pp4 and "require_device_tp_all_reduce=" in pp4)
check("parallel_state has DS4 PP CPU-staged tensor-dict path", "TensorMetadataCpuStaged" in ps and "_should_cpu_stage_ds4_pp_tensor_dict" in ps)
check("relaunch supports PP4xTP2xEP service", "dsv4-pp4-tp2-ep" in relaunch)
check("relaunch validates PP4xTP2 launcher and speed audit", "ds4_launch_dsv4_flash_pp4_tp2_ep.sh" in relaunch and "ds4_speed_path_audit.py" in relaunch)
check("stop script catches PP4xTP2 launcher", "pp4_tp2_ep" in stop)
check("stop script catches stale NCCL preflight processes", "ds4_nccl_preflight" in stop)
check("relaunch fails early when head startup process exits", "startup-fail-fast-s" in relaunch and "head_service_process_alive" in relaunch)
check("relaunch process probe avoids pgrep self-match", "[d]s4_nccl_preflight.py" in relaunch and "[v]llm.entrypoints" in relaunch)
check("DS4 PR helper pushes to the experiencenow fork, not upstream origin", 'DEFAULT_PUSH_REMOTE = "experiencenow"' in submit_pr and 'DEFAULT_REPO = "experiencenow-ai/vllm"' in submit_pr and "does not point at experiencenow-ai/vllm" in submit_pr)
check("DS4 PR helper refuses non-DS4 target repos", "refusing target repo" in submit_pr and "experiencenow-ai/vllm" in submit_pr)
