#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text()


def check(name: str, ok: bool) -> None:
    print(("PASS" if ok else "FAIL") + ": " + name)
    if not ok:
        raise SystemExit(1)


pp8 = read("tools/ds4_launch_dsv4_flash_pp8.sh")
pp4 = read("tools/ds4_launch_dsv4_flash_pp4_tp2_ep.sh")
guard = read("tools/ds4_200g_guard.sh")
preflight = read("tools/ds4_nccl_preflight.py")
nccl_p2p_bench = read("tools/ds4_nccl_p2p_bench.py")
nccl_p2p_runner = read("tools/ds4_run_nccl_p2p_bench.py")
nccl_p2p_line_sweep = read("tools/ds4_run_nccl_p2p_line_sweep.py")
rail_tcp = read("tools/ds4_rail_tcp_preflight.py")
relaunch = read("tools/ds4_relaunch_spark_service.py")
stop = read("tools/ds4_stop_spark_processes.py")
submit_pr = read("tools/ds4_submit_pr.py")
envs = read("vllm/envs.py")
ps = read("vllm/distributed/parallel_state.py")

check("PP8 defaults to PyNCCL CUDA PP tensor-dict path", 'VLLM_DS4_PP_TORCH_PG_TENSOR_DICT:-0' in pp8 and 'VLLM_DS4_PP_TORCH_PAIR_GROUPS:-0' in pp8 and 'VLLM_DS4_PP_TORCH_GROUP_WARMUP:-0' in pp8 and 'VLLM_DS4_PP_PYNCCL_TENSOR_DICT:-1' in pp8)
check("PP8 exports deterministic PP edge rail hints for adjacent NCCL pairs", "VLLM_DS4_PP_EDGE_RAIL" in pp8 and "DS4_NCCL_PREFLIGHT_PP_EDGE_RAIL" in pp8 and "ds4_pp_edge_ifname" in pp8 and "pp_edge_rail=" in pp8)
check("PP8 keeps PyNCCL tensor-dict chunking configured for explicit opt-in tests", 'VLLM_DS4_PP_PYNCCL_TENSOR_DICT_STRIPES:-8' in pp8)
check("PP8 keeps PyNCCL P2P credit disabled by default for bidirectional preflight", 'VLLM_DS4_PP_PYNCCL_P2P_CREDIT:-0' in pp8)
check("PP8 skips PyNCCL all-reduce warmup while keeping send/recv enabled", 'VLLM_DS4_SKIP_PYNCCL_WARMUP_ALLREDUCE:-1' in pp8 and 'VLLM_DS4_PP_PYNCCL_TENSOR_DICT:-1' in pp8)
check("PP8 keeps independent multi-communicator striping opt-in", 'VLLM_DS4_PP_STRIPED_NCCL_TENSOR_DICT:-0' in pp8)
check("PP8 keeps the PP device communicator enabled by default", 'VLLM_DS4_PP_DISABLE_DEVICE_COMMUNICATOR:-0' in pp8)
check("PP8 requires CUDA device metadata for PP tensor dicts", 'VLLM_DS4_PP_DEVICE_TENSOR_DICT_METADATA:-1' in pp8 and "Pickled CPU PP metadata caused multi-second stage stalls" in pp8)
check("PP8 traces unavoidable runtime communicator startup", 'VLLM_DS4_COMM_GROUP_TRACE:-1' in pp8 and 'VLLM_DS4_COMM_GROUP_TIMEOUT_SECONDS:-180' in pp8)
check("torch ProcessGroup CUDA tensor-dict env exists as measured PP path", "VLLM_DS4_PP_TORCH_PG_TENSOR_DICT" in envs)
check("torch pair-group tensor-dict env exists for route-local PP edges", "VLLM_DS4_PP_TORCH_PAIR_GROUPS" in envs)
check("broad torch PP tensor-dict path warms its NCCL device group", "VLLM_DS4_PP_TORCH_GROUP_WARMUP" in envs and "_warm_ds4_pp_torch_device_group" in ps and "DS4 PP broad torch device group warmed" in ps)
check("PyNCCL tensor-dict env exists as explicit experimental path", "VLLM_DS4_PP_PYNCCL_TENSOR_DICT" in envs)
check("PP device tensor-dict metadata env exists", "VLLM_DS4_PP_DEVICE_TENSOR_DICT_METADATA" in envs)
check("PyNCCL tensor-dict striping env exists", "VLLM_DS4_PP_PYNCCL_TENSOR_DICT_STRIPES" in envs)
check("PyNCCL P2P credit env exists", "VLLM_DS4_PP_PYNCCL_P2P_CREDIT" in envs)
check("PP tensor-dict TP all-gather env exists", "VLLM_DS4_PP_TENSOR_DICT_TP_ALL_GATHER" in envs)
check("TP process-group all-reduce escape hatch env exists", "VLLM_DS4_TP_PROCESS_GROUP_ALL_REDUCE" in envs)
check("TP device all-reduce requirement env exists", "VLLM_DS4_REQUIRE_DEVICE_TP_ALL_REDUCE" in envs)
check("static PP edge envs are registered with vLLM env validation", all(name in envs for name in ("VLLM_DS4_PP_EDGE_RAIL", "VLLM_DS4_PP_PREV_SOCKET_IFNAME", "VLLM_DS4_PP_NEXT_SOCKET_IFNAME", "VLLM_DS4_PP_SOCKET_IFNAME")))
check("distributed startup trace envs are registered", "VLLM_DS4_COMM_GROUP_TRACE" in envs and "VLLM_DS4_COMM_GROUP_TIMEOUT_SECONDS" in envs and "VLLM_DS4_COMM_GROUP_WARN_SECONDS" in envs)
check("parallel_state has DS4 PP PyNCCL tensor-dict gate", "_can_use_ds4_pynccl_tensor_dict" in ps or "_can_use_ds4_pp_pynccl_tensor_dict" in ps)
check("parallel_state logs Torch group creation begin/done", "DS4 comm group create begin" in ps and "DS4 comm group create done" in ps and "_new_ds4_process_group" in ps)
check("parallel_state logs device communicator creation begin/done", "DS4 device communicator create begin" in ps and "DS4 device communicator create done" in ps and "_new_ds4_device_communicator" in ps)
check("parallel_state logs and bounds initial world init", "DS4 world init begin" in ps and "DS4 world init done" in ps and "VLLM_DS4_COMM_GROUP_TIMEOUT_SECONDS" in ps and "init_process_group(" in ps)
check("PyNCCL logs unique-id broadcast and ncclCommInitRank", "DS4 PyNCCL unique-id broadcast begin" in read("vllm/distributed/device_communicators/pynccl.py") and "DS4 PyNCCL ncclCommInitRank begin" in read("vllm/distributed/device_communicators/pynccl.py"))
check("parallel_state has DS4 PP CUDA metadata header path", "_send_ds4_pp_device_metadata" in ps and "_recv_ds4_pp_device_metadata" in ps)
check("parallel_state builds route-local adjacent torch NCCL pair groups", "_build_ds4_pp_torch_pair_groups" in ps and "VLLM_DS4_PP_NEXT_SOCKET_IFNAME" in ps and "VLLM_DS4_PP_PREV_SOCKET_IFNAME" in ps and "_warm_ds4_pp_torch_pair_group" in ps)
check("parallel_state builds PP torch pair groups collectively across all ranks", "Build adjacent NCCL pair groups collectively" in ps and "use_local_synchronization=True" not in ps)
check("parallel_state uses pair-local PP NCCL ifnames for torch edge groups", "_ds4_pp_pair_nccl_socket_ifname" in ps and "os.environ[\"NCCL_SOCKET_IFNAME\"] = pair_ifname" in ps and "_ds4_pp_socket_ifnames" not in ps)
check("parallel_state warms PP torch pair groups with P2P, not all-reduce", "_warm_ds4_pp_torch_pair_group" in ps and "batch_isend_irecv" in ps and "DS4 PP torch pair group P2P warmup failed" in ps and "torch.distributed.all_reduce(\n            value, op=torch.distributed.ReduceOp.SUM, group=pair_group" not in ps)
check("parallel_state can send DS4 PP CUDA metadata over torch pair groups", "VLLM_DS4_PP_TORCH_PG_TENSOR_DICT" in ps and "_ds4_pp_torch_pair_group(dst)" in ps and "_ds4_pp_torch_pair_group(src)" in ps and "group=pair_group" in ps)
check("parallel_state avoids CPU object metadata on DS4 PP device metadata path", "VLLM_DS4_PP_DEVICE_TENSOR_DICT_METADATA" in ps and "Refusing CPU/Gloo metadata fallback" in ps)
check("parallel_state stripes DS4 PP PyNCCL tensor-dict payloads", "_ds4_pynccl_p2p_chunks" in ps)
check("parallel_state keeps reverse credit available for unidirectional PyNCCL P2P", "VLLM_DS4_PP_PYNCCL_P2P_CREDIT" in ps and "credit_op" in ps)
check("parallel_state queues DS4 PP PyNCCL on a dedicated CUDA comm stream", "_get_ds4_pp_pynccl_stream" in ps and "torch.cuda.stream(comm_stream)" in ps)
check("parallel_state keeps receive payload waits stream-ordered", "_Ds4CudaStreamHandle" in ps and "torch.cuda.current_stream().wait_event(self._event)" in ps)
check("parallel_state keeps PP payload sends stream-ordered in conveyor mode", "cuda_p2p_tensors,\n            dst,\n            torch.distributed.isend," in ps and "synchronize_on_wait=not envs.VLLM_DS4_PP_OVERLAP_SEND" in ps)
check("parallel_state sends DS4 PP metadata without waiting for the model stream", "wait_for_producer=False" in ps and "synchronize_on_wait=True" in ps)
check("parallel_state posts DS4 PP payload receives without waiting for local compute", "torch.distributed.irecv,\n            wait_for_producer=False" in ps)
check("parallel_state can disable PP tensor-dict TP all-gather", "VLLM_DS4_PP_TENSOR_DICT_TP_ALL_GATHER" in ps and 'self.unique_name.startswith("pp")' in ps)
check("parallel_state keeps DS4 TP process-group all-reduce opt-in only", "VLLM_DS4_TP_PROCESS_GROUP_ALL_REDUCE" in ps and 'self.unique_name.startswith("tp:")' in ps and "torch.distributed.all_reduce(output, group=self.device_group)" in ps)
check("CUDA communicator refuses TP process-group fallback when DS4 requires device all-reduce", "VLLM_DS4_REQUIRE_DEVICE_TP_ALL_REDUCE" in read("vllm/distributed/device_communicators/cuda_communicator.py") and "refusing torch process-group fallback for TP group" in read("vllm/distributed/device_communicators/cuda_communicator.py"))
check("PP4xTP2 launcher exists", 'TP_SIZE="${TP_SIZE:-2}"' in pp4 and 'PP_SIZE="${PP_SIZE:-4}"' in pp4)
check("PP4xTP2 launcher enforces 8x world geometry", 'requires NNODES=8 PP_SIZE=4 TP_SIZE=2' in pp4)
check("PP4xTP2 launcher enables expert parallel", "--enable-expert-parallel" in pp4)
check("PP4xTP2 launcher has 43-layer partition", 'DSV4_FLASH_PP_LAYER_PARTITION="7,11,14,11"' in pp4)
check("PP4xTP2 launcher defaults to bounded request admission waves", 'DSV4_SCHED_MAX_NEW_REQS_PER_STEP:-32' in pp4)
check("PP4xTP2 launcher defaults to bounded prefill token waves", 'DSV4_SCHED_MAX_NEW_PREFILL_TOKENS_PER_STEP:-32768' in pp4)
check("PP8 throughput profile uses conveyor-shaped request admission waves", 'DSV4_SCHED_MAX_NEW_REQS_PER_STEP:=64' in pp8)
check("PP8 throughput profile uses bounded mixed-prefill token waves", 'DSV4_SCHED_MAX_NEW_PREFILL_TOKENS_PER_STEP:=65536' in pp8)
check("PP8 default profile is max-length/max-KV, not compact bringup", 'DS4_DSV4_PIPELINE_RAM_PROFILE="${DS4_DSV4_PIPELINE_RAM_PROFILE:-max-kv}"' in pp8 and 'default=os.getenv("DS4_DSV4_PIPELINE_RAM_PROFILE", "max-kv")' in relaunch)
check("PP8 max-throughput aliases use 256K context and larger KV cap", "max-kv|MAX-KV|max-length|MAX-LENGTH|max-throughput|MAX-THROUGHPUT|batch512|BATCH512" in pp8 and 'DSV4_MAX_MODEL_LEN:=262144' in pp8 and 'DSV4_KV_CACHE_MEMORY_BYTES:=68719476736' in pp8)
check("PP8 throughput profile redlines cold-prefill KV pressure", "VLLM_DS4_SCHED_KV_ADMISSION_MAX_USAGE" in envs and "VLLM_DS4_SCHED_KV_HARD_FAIL_USAGE" in envs and 'DSV4_SCHED_KV_ADMISSION_MAX_USAGE:=0.90' in pp8 and "new_cold_prefill_admission" in read("vllm/v1/core/sched/scheduler.py"))
check("PP8 launcher hard-codes the front-loaded 43-layer partition", 'DSV4_FLASH_PP_LAYER_PARTITION="8,8,8,8,8,1,1,1"' in pp8)
check("PP8 launcher does not accept stale default partition overrides", "DSV4_FLASH_PP_LAYER_PARTITION_DEFAULT" not in pp8)
check("PP8 launcher scales KV cache bytes by local layer ownership", "DSV4_SCALE_KV_CACHE_BY_LOCAL_LAYERS" in pp8 and "DSV4_KV_CACHE_MEMORY_BYTES_EFFECTIVE" in pp8 and "local_layers=$DSV4_LOCAL_LAYER_COUNT" in pp8)
check("PP8 launcher keeps a per-profile KV floor for thin stages", "DSV4_MIN_KV_CACHE_MEMORY_BYTES" in pp8 and "kv_cache_memory_bytes_min=" in pp8)
check("PP8 launcher passes the effective rank-local KV cap to vLLM", 'KV_CACHE_MEMORY_ARGS=(--kv-cache-memory-bytes "$DSV4_KV_CACHE_MEMORY_BYTES_EFFECTIVE")' in pp8)
check("DSV4 launchers skip profile-only dummy sampler logits gather", "VLLM_DS4_PROFILE_SKIP_DUMMY_SAMPLER" in envs and 'VLLM_DS4_PROFILE_SKIP_DUMMY_SAMPLER:-1' in pp8 and 'VLLM_DS4_PROFILE_SKIP_DUMMY_SAMPLER:-1' in pp4)
check("DSV4 launchers skip explicit-KV memory profile forward", "VLLM_DS4_SKIP_EXPLICIT_KV_PROFILE_RUN" in envs and 'VLLM_DS4_SKIP_EXPLICIT_KV_PROFILE_RUN:-1' in pp8 and 'VLLM_DS4_SKIP_EXPLICIT_KV_PROFILE_RUN:-1' in pp4)
check("DSV4 PP8 lets throughput profiles warm last-rank sampler", "VLLM_DS4_SKIP_LAST_RANK_SAMPLER_WARMUP" in envs and "DSV4_SKIP_LAST_RANK_SAMPLER_WARMUP:=0" in pp8 and 'VLLM_DS4_SKIP_LAST_RANK_SAMPLER_WARMUP:-${DSV4_SKIP_LAST_RANK_SAMPLER_WARMUP:-1}' in pp8)
check("PP4xTP2 launcher preserves final-only nonstreaming output", "VLLM_DS4_FINAL_ONLY_NONSTREAMING" in pp4)
check("PP4xTP2 launcher preserves fused execute/sample default", "VLLM_DS4_FUSED_EXECUTE_SAMPLE" in pp4)
check("PP4xTP2 launcher serves existing DS4 DSV4 API model by default", 'DSV4_SERVED_MODEL_NAME:-deepseek-v4-flash-pp8' in pp4)
check("PP4xTP2 launcher does not set PP-only global backend", 'export VLLM_DS4_PP_ONLY_GLOBAL_BACKEND=' not in pp4)
check("PP4xTP2 launcher fails early if PP-only global backend leaks in", "PP4xTP2xEP refuses VLLM_DS4_PP_ONLY_GLOBAL_BACKEND" in pp4)
check("PP4xTP2 launcher uses NCCL for global control", 'VLLM_DS4_DISTRIBUTED_BACKEND="${VLLM_DS4_DISTRIBUTED_BACKEND:-nccl}"' in pp4)
check("PP4xTP2 launcher refuses gloo/CPU global control", "gloo/CPU control paths hide PP transport regressions" in pp4)
check("PP4xTP2 launcher preflights required TP groups and PP P2P links", 'DS4_NCCL_PREFLIGHT_MODE="${DS4_NCCL_PREFLIGHT_MODE:-p2p_nccl}"' in pp4 and "DS4_NCCL_PREFLIGHT_GROUPS" in pp4)
check("PP4xTP2 launcher declares TP/EP pair collectives", "0,1;2,3;4,5;6,7" in pp4)
check("PP4xTP2 launcher declares directional PP boundary P2P pairs", "0-2;1-3;2-4;3-5;4-6;5-7" in pp4)
check("PP4xTP2 launcher uses unidirectional PP P2P preflight", 'DS4_NCCL_PREFLIGHT_P2P_DIRECTION="${DS4_NCCL_PREFLIGHT_P2P_DIRECTION:-unidirectional}"' in pp4)
check("PP4xTP2 launcher refuses pair-local NCCL view", "refuses DS4_200G_PAIR_LOCAL_NCCL=1" in pp4)
check("200G guard separates route validation IFNAME from NCCL IFNAME", "DS4_200G_NCCL_IFNAME" in guard and "nccl_ifnames_csv" in guard and "NCCL interface" in guard)
check("200G guard defaults NCCL socket transport to physical rail interfaces", 'socket_ifname="${DS4_200G_SOCKET_IFNAME:-$ifnames_csv}"' in guard and "NCCL routed socket interface" in guard)
check("200G guard pins IB HCA from NCCL IFNAME, not the full route list", 'ds4_200g_check_or_export NCCL_IB_HCA "$nccl_hcas_csv"' in guard)
check("200G guard supports explicit degraded-link bringup without hiding it", "DS4_200G_ALLOW_DEGRADED_LINKS" in guard and "excluding it from the effective DS4 fabric list" in guard)
check("200G guard uses configurable link-speed floor before measured TCP preflight", "DS4_200G_LINK_MIN_MBPS" in guard and "below DS4_200G_LINK_MIN_MBPS" in guard)
check("200G guard prints effective fabric list after degraded filtering", "effective DS4_200G_IFNAME" in guard and "effective DS4_200G_NCCL_IFNAME" in guard)
check("200G guard auto-selects reboot-safe control interface", "ds4_200g_resolve_control_ifname" in guard and 'requested="${DS4_CONTROL_IFNAME:-auto}"' in guard and "DS4_200G_EFFECTIVE_CONTROL_IFNAME" in guard)
check("200G guard keeps multi-node Gloo off loopback and routed /32 aliases", "ds4_200g_resolve_gloo_ifname" in guard and "ds4_200g_find_management_ifname" in guard and "ds4_200g_is_gloo_loopback_like_ifname" in guard and "ds4ring*" in guard and "multi-node Gloo control cannot bind to" in guard and "DS4_200G_EFFECTIVE_GLOO_IFNAME" in guard)
check("200G guard lets routed loopback advertise coexist with management Gloo", 'DS4_GLOO_SOCKET_IFNAME:-auto' in guard and 'ds4_200g_check_or_export GLOO_SOCKET_IFNAME "$gloo_ifname"' in guard)
check("200G guard scales P2P NCCL preflight timeout by declared edge count", "DS4_NCCL_PREFLIGHT_P2P_TIMEOUT_PER_PAIR" in guard and "p2p_pair_count" in guard and 'DS4_NCCL_PREFLIGHT_TIMEOUT="$effective_timeout_s"' in guard and "timeout_s=$effective_timeout_s" in guard)
check("DSV4 and Qwen launchers default to all physical rail names", all("enp1s0f0np0,enp1s0f1np1,enP2p1s0f0np0,enP2p1s0f1np1" in script and 'DS4_CONTROL_IFNAME:-auto' in script for script in (pp8, pp4, read("tools/ds4_launch_qwen27_nvfp4_pp8.sh"), read("tools/ds4_launch_qwen27_pp8.sh"))))
check("NCCL preflight banner prints configured and effective interface lists", "configured_if=$DS4_200G_IFNAME" in guard and "effective_if=${DS4_200G_EFFECTIVE_IFNAME" in guard and "effective_nccl_if=${DS4_200G_EFFECTIVE_NCCL_IFNAME" in guard)
check("NCCL preflight prints NCCL interface override", '"DS4_200G_NCCL_IFNAME"' in preflight)
check("NCCL preflight has P2P bandwidth mode", "def _run_p2p_nccl_preflight(" in preflight and "DS4_NCCL_PREFLIGHT_P2P_PAIRS" in preflight)
check("NCCL preflight stripes P2P probes to match PP tensor transport", "DS4_NCCL_PREFLIGHT_P2P_STRIPES" in preflight and "_split_p2p_tensor" in preflight)
check("NCCL preflight separates directional PP P2P from TP pair collectives", "DS4_NCCL_PREFLIGHT_P2P_DIRECTION" in preflight and "pairwise NCCL group probes begin" in preflight)
check("P2P preflight can skip world all-reduce on open-line PP-only topology", "def _bool_env(" in preflight and "DS4_NCCL_PREFLIGHT_P2P_SKIP_WORLD_ALLREDUCE" in preflight and "communicator all_reduce skipped" in preflight)
check("P2P preflight can test broad world NCCL P2P without adjacent pair groups", "torch_world" in preflight and "broad NCCL torch group create begin" in preflight and 'backend="nccl"' in preflight and "torch_group = broad_torch_group" in preflight)
check("DSV4 PP8 skips full-world broad NCCL warmup on open-line topology", 'DS4_NCCL_PREFLIGHT_TORCH_WORLD_WARMUP:-0' in pp8 and 'VLLM_DS4_PP_TORCH_GROUP_WARMUP:-0' in pp8)
check("P2P preflight creates collective torch NCCL edge groups", "_new_nccl_pair_group" in preflight and "Create every adjacent pair group collectively" in preflight and "use_local_synchronization=True" not in preflight and "return None" in preflight and "_pp_edge_dev_for_rank(rank, peer)" in preflight)
check("P2P preflight uses deterministic pair-local torch ifnames and P2P warmup", "DS4_NCCL_PREFLIGHT_PP_EDGE_RAIL" in preflight and "edge_rail=" in preflight and "pair_nccl_ifname" in preflight and "os.environ[\"NCCL_SOCKET_IFNAME\"] = route_ifname" in preflight and "_stable_torch_pair_ifnames" not in preflight and "batch_isend_irecv(ops)" in preflight and "torch pair warmup failed" in preflight and "dist.all_reduce(value, op=dist.ReduceOp.SUM, group=pair_group)" not in preflight)
check("P2P preflight pins PyNCCL pairs to the active adjacent edge interface", "DS4 NCCL P2P preflight PyNCCL pair route" in preflight and "pair_nccl_ifname=" in preflight and "PyNcclCommunicator(cpu_group" in preflight)
check("standalone NCCL P2P bench compares torch PyNCCL and striped paths", "method == \"torch\"" in nccl_p2p_bench and "method == \"pynccl\"" in nccl_p2p_bench and "method == \"striped\"" in nccl_p2p_bench)
check("standalone NCCL P2P bench can reproduce symmetric PyNCCL credit mode", "DS4_NCCL_P2P_BENCH_CREDIT" in nccl_p2p_bench and '"credit"' in nccl_p2p_bench)
check("standalone NCCL P2P runner can isolate GPUs before transport tests", "--stop-service" in nccl_p2p_runner and "ds4_stop_spark_processes.py" in nccl_p2p_runner)
check("standalone NCCL P2P runner defaults to PyNCCL credit and warmup", "--pynccl-credit" in nccl_p2p_runner and '"DS4_NCCL_P2P_BENCH_CREDIT": "1" if args.pynccl_credit else "0"' in nccl_p2p_runner and '"VLLM_DS4_SKIP_PYNCCL_WARMUP_ALLREDUCE": "0"' in nccl_p2p_runner)
check("standalone NCCL P2P line sweep tests one physical edge per 2-rank world", "ds4_run_nccl_p2p_bench.py" in nccl_p2p_line_sweep and "EDGES" in nccl_p2p_line_sweep and "NCCL_NET=Socket" in nccl_p2p_line_sweep)
check("NCCL collective bandwidth is warning-only during cable debug", "DS4_NCCL_PREFLIGHT_MIN_BUSBW_GBPS:-0" in guard)
check("NCCL preflight warns below old collective floor without failing launch", "DS4_NCCL_PREFLIGHT_WARN_BUSBW_GBPS" in preflight and "WARNING: DS4 NCCL preflight below warning threshold" in preflight and "DS4_NCCL_PREFLIGHT_WARN_BUSBW_GBPS:-8" in guard)
check("rail TCP preflight script exists", "ds4_transfer.fast_copy data-plane shape" in rail_tcp)
check("rail TCP preflight discovers route rails like fast_copy", "ip\", \"route\", \"show\"" in rail_tcp and "destination_ip=dst_ip" in rail_tcp)
check("rail TCP preflight uses iperf for the launch speed gate", "DS4_RAIL_TCP_PREFLIGHT_TOOL" in rail_tcp and "iperf" in rail_tcp and "--reportstyle C" not in rail_tcp and "-y" in rail_tcp)
check("rail TCP iperf parser uses the aggregate summary row", 'fields[5] != "-1"' in rail_tcp)
check("rail TCP iperf parser rejects zero-interval summaries", "DS4_RAIL_TCP_PREFLIGHT_MIN_REPORT_INTERVAL_S" in rail_tcp and "interval_s < min_interval_s" in rail_tcp)
check("rail TCP background servers verify their own bandwidth summaries", "DS4_RAIL_TCP_PREFLIGHT_VERIFY_SERVER_SUMMARY" in rail_tcp and "_parse_background_server_bits_per_second" in rail_tcp and "rail TCP preflight server did not produce a verified summary" in rail_tcp)
check("rail TCP preflight holds inbound servers for the measurement window", "DS4_RAIL_TCP_PREFLIGHT_SERVER_HOLD_EXTRA_S" in rail_tcp and "hold_until = server_started_at + duration_s + hold_extra_s" in rail_tcp)
check("rail TCP preflight keeps servers alive long enough for slow ring ranks", 'DS4_RAIL_TCP_PREFLIGHT_SERVER_HOLD_EXTRA_S", "10.0"' in rail_tcp)
check("rail TCP clients retry until peer servers are ready", "DS4_RAIL_TCP_PREFLIGHT_CLIENT_RETRY_SLEEP_S" in rail_tcp and "while time.monotonic() < deadline" in rail_tcp)
check("rail TCP hard floor is expressed in Gbit/s", "DS4_RAIL_TCP_PREFLIGHT_MIN_GBIT_S" in rail_tcp and "fail_Gbit_s" in rail_tcp)
check("rail TCP warning floor prints measured Gbit/s without failing launch", "DS4_RAIL_TCP_PREFLIGHT_WARN_GBIT_S" in rail_tcp and "WARNING: DS4 rail TCP preflight below warning threshold" in rail_tcp)
check("rail TCP preflight binds explicit client source rail IPs", "nc -N -s {rail.source_ip}" in rail_tcp)
check("rail TCP preflight refuses Wi-Fi/non-fabric routes before bandwidth tests", "_reject_forbidden_rail" in rail_tcp and "refused Wi-Fi route" in rail_tcp and "DS4_RAIL_TCP_ALLOWED_IFNAME" in rail_tcp)
check("rail TCP preflight uses many unencrypted streams per edge", "DS4_RAIL_TCP_PREFLIGHT_STREAMS" in rail_tcp and "threading.Thread" in rail_tcp)
check("200G guard can run rail TCP preflight before NCCL", "ds4_run_rail_tcp_preflight" in guard and "ds4_rail_tcp_preflight.py" in guard)
check("Triton/AOT cache scope is derived from vLLM commit", "ds4_vllm_git_commit()" in guard and "git -C \"$root\" rev-parse --short=12 HEAD" in guard)
check("Triton/AOT cache scope includes launch shape", "ds4_triton_cache_scope()" in guard and "DSV4_FLASH_PP_LAYER_PARTITION" in guard and "DSV4_MAX_NUM_SEQS" in guard and "DSV4_MAX_NUM_BATCHED_TOKENS" in guard)
check("Triton/AOT cache root is scoped below the service root", 'default_work_root="$default_work_base/$cache_scope"' in guard and 'export DS4_TRITON_CACHE_SCOPE="$cache_scope"' in guard)
check("Triton/AOT cache log prints cache scope and VLLM cache root", "cache_scope=$DS4_TRITON_CACHE_SCOPE" in guard and "VLLM_CACHE_ROOT=$VLLM_CACHE_ROOT" in guard)
check("DSV4 PP8 enables rail TCP fabric preflight", "DS4_RAIL_TCP_PREFLIGHT_ACTIVE" in pp8 and "ds4_run_rail_tcp_preflight" in pp8)
check("DSV4 PP8 allows disconnected endpoint rails while measured open-line rails remain fail-closed", 'DS4_200G_ALLOW_DEGRADED_LINKS:-1' in pp8)
check("DSV4 PP8 rail TCP default fails below 10 Gbit/s and warns below old floor", "DS4_RAIL_TCP_PREFLIGHT_MIN_GBIT_S:-10" in pp8 and "DS4_RAIL_TCP_PREFLIGHT_WARN_GBIT_S:-64" in pp8)
check("DSV4 PP8 rail TCP default uses the open 8-node line, not a missing 7-0 ring edge", "0-1;1-2;2-3;3-4;4-5;5-6;6-7" in pp8 and "6-7;7-0" not in pp8)
check("DSV4 PP8 defaults NCCL preflight to the same PyNCCL PP send/recv path used at runtime", "DS4_NCCL_PREFLIGHT_MODE:-p2p_nccl" in pp8 and "DS4_NCCL_PREFLIGHT_P2P_METHOD:-pynccl" in pp8 and "DS4_NCCL_PREFLIGHT_P2P_SKIP_WORLD_ALLREDUCE:-1" in pp8 and "DS4_NCCL_PREFLIGHT_P2P_STRIPES" in pp8 and "DS4_NCCL_PREFLIGHT_P2P_CREDIT" in pp8 and "DS4_NCCL_PREFLIGHT_P2P_PAIRS" in pp8)
check("DSV4 PP8 defaults PyNCCL preflight to bidirectional no-credit exchange", 'DS4_NCCL_PREFLIGHT_P2P_DIRECTION="${DS4_NCCL_PREFLIGHT_P2P_DIRECTION:-bidirectional}"' in pp8 and 'VLLM_DS4_PP_PYNCCL_P2P_CREDIT="${VLLM_DS4_PP_PYNCCL_P2P_CREDIT:-0}"' in pp8)
check("DSV4 PP4xTP2 enables rail TCP physical fabric preflight", "DS4_RAIL_TCP_PREFLIGHT_ACTIVE" in pp4 and "DS4_RAIL_TCP_PREFLIGHT_PAIRS" in pp4)
check("DSV4 PP4xTP2 allows disconnected endpoint rails while measured open-line rails remain fail-closed", 'DS4_200G_ALLOW_DEGRADED_LINKS:-1' in pp4)
check("DSV4 PP4xTP2 rail TCP default uses the open 8-node line, not a missing 7-0 ring edge", "0-1;1-2;2-3;3-4;4-5;5-6;6-7" in pp4 and "6-7;7-0" not in pp4)
check("DSV4 PP4xTP2 keeps NCCL P2P bandwidth warning-only during cable debug", 'DS4_NCCL_PREFLIGHT_MIN_P2P_GBPS="${DS4_NCCL_PREFLIGHT_MIN_P2P_GBPS:-0}"' in pp4 and "DS4_NCCL_PREFLIGHT_WARN_P2P_GBPS" in pp4 and "WARNING: DS4 NCCL P2P preflight below warning threshold" in preflight)
check("PP4xTP2 launcher refuses CPU-staged PP tensor dict fallback", "refuses VLLM_DS4_PP_CPU_STAGED_TENSOR_DICT=1" in pp4)
check("PP4xTP2 launcher defaults to PyNCCL CUDA tensor-dict path", 'VLLM_DS4_PP_TORCH_PG_TENSOR_DICT:-0' in pp4 and 'VLLM_DS4_PP_PYNCCL_TENSOR_DICT:-1' in pp4)
check("PP4xTP2 launcher refuses missing CUDA PP tensor-dict path", "requires a CUDA PP tensor-dict path" in pp4)
check("PP4xTP2 launcher requires PP device metadata fast path", "requires VLLM_DS4_PP_DEVICE_TENSOR_DICT_METADATA=1" in pp4 and 'VLLM_DS4_PP_DEVICE_TENSOR_DICT_METADATA:-1' in pp4)
check("PP4xTP2 launcher disables PP tensor-dict TP all-gather", 'VLLM_DS4_PP_TENSOR_DICT_TP_ALL_GATHER:-0' in pp4 and "refuses VLLM_DS4_PP_TENSOR_DICT_TP_ALL_GATHER=1" in pp4)
check("PP4xTP2 launcher keeps PyNCCL chunking configured for opt-in tests", 'VLLM_DS4_PP_PYNCCL_TENSOR_DICT_STRIPES:-8' in pp4)
check("PP4xTP2 launcher enables symmetric PyNCCL P2P credit by default", 'VLLM_DS4_PP_PYNCCL_P2P_CREDIT:-1' in pp4)
check("PP4xTP2 launcher keeps PyNCCL warmup enabled by default", 'VLLM_DS4_SKIP_PYNCCL_WARMUP_ALLREDUCE:-0' in pp4)
check("PP4xTP2 launcher defaults TP all-reduce to the device communicator", 'VLLM_DS4_TP_PROCESS_GROUP_ALL_REDUCE:-0' in pp4 and 'VLLM_DS4_REQUIRE_DEVICE_TP_ALL_REDUCE:-1' in pp4 and "require_device_tp_all_reduce=" in pp4)
check("parallel_state has DS4 PP CPU-staged tensor-dict path", "TensorMetadataCpuStaged" in ps and "_should_cpu_stage_ds4_pp_tensor_dict" in ps)
check("relaunch supports PP4xTP2xEP service", "dsv4-pp4-tp2-ep" in relaunch)
check("relaunch validates PP4xTP2 launcher and speed audit", "ds4_launch_dsv4_flash_pp4_tp2_ep.sh" in relaunch and "ds4_speed_path_audit.py" in relaunch)
check("relaunch cleans stale local controllers without broad pkill patterns", "cleanup_stale_local_controllers" in relaunch and "ds4_relaunch_spark_service.py" in relaunch and "os.kill(pid, signal.SIGKILL)" in relaunch)
check("stop script catches PP4xTP2 launcher", "pp4_tp2_ep" in stop)
check("stop script catches stale NCCL preflight processes", "ds4_nccl_preflight" in stop)
check("relaunch fails early when head startup process exits", "startup-fail-fast-s" in relaunch and "head_service_process_alive" in relaunch)
check("relaunch process probe avoids pgrep self-match", "[d]s4_nccl_preflight.py" in relaunch and "[v]llm.entrypoints" in relaunch)
check("DS4 PR helper pushes to the experiencenow fork, not upstream origin", 'DEFAULT_PUSH_REMOTE = "experiencenow"' in submit_pr and 'DEFAULT_REPO = "experiencenow-ai/vllm"' in submit_pr and "does not point at experiencenow-ai/vllm" in submit_pr)
check("DS4 PR helper refuses non-DS4 target repos", "refusing target repo" in submit_pr and "experiencenow-ai/vllm" in submit_pr)
check("DS4 PR helper syncs local main from experiencenow after merge", "sync_base" in submit_pr and 'run(["git", "pull", remote, base])' in submit_pr and "--no-sync-main" in submit_pr)
